In [19]:
import pandas as pd
train_graph = '../data/corpus_graphs/trex_triples_filtered_ilpc_train.txt'
test_graph = '../data/ilpc/raw/small/inference_test.txt'

train_triple_df = pd.read_csv(train_graph, delimiter='\t', header=None)
train_triples = list(train_triple_df.itertuples(index=False, name=None))

test_triple_df = pd.read_csv(test_graph, delimiter='\t', header=None)
test_triples = list(test_triple_df.itertuples(index=False, name=None))


## Compute the overlap of triples in the LP test set with the triples in our graph

In [1]:
len(set(train_triples).intersection(set(test_triples)))

NameError: name 'train_triples' is not defined

In [23]:
import torch
bs = 10

In [24]:
x = torch.ones((bs, 768))

In [25]:
x_re = x.reshape((bs, 1, 2,-1))
x_re.size()

torch.Size([10, 1, 2, 384])

In [26]:
conv1 = torch.nn.Conv2d(1, bs, (2, 2), 4, 0)
x_conv = torch.relu(conv1(x_re))
x_conv.size()

x_conv = dropout(x_conv)

torch.Size([10, 10, 1, 96])

In [29]:
x_flat = x_conv.flatten().reshape((bs, -1))
x_flat.size()

In [31]:
embedding_dim = 500
linear = torch.nn.Linear(960, embedding_dim)

In [32]:
x_final = linear(x_flat)

In [34]:
x_final.size()

torch.Size([10, 500])

In [1]:
import torch

In [4]:
x=torch.tensor([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [6]:
x.flatten().reshape((2, -1))

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12]])

In [9]:
import torch

x = torch.tensor([[1.9604e-02,  6.2937e-02,  1.1282e-02, -1.2976e-02,  3.4542e-02,
        -6.2316e-03,  7.3689e-03,  1.5995e-02, -2.9797e-02,  1.3459e-02,
         2.1407e-02, -9.6071e-03]])
bs = x.size(0)

x = x.reshape((bs, 1, 2,-1))
print(x)

conv1 = torch.nn.Conv2d(1, 1, (2, 1), 1, 0)
torch.nn.init.xavier_uniform(conv1.weight)

xs_head = torch.sigmoid(conv1(x))
print(xs_head)

tensor([[[[ 0.0196,  0.0629,  0.0113, -0.0130,  0.0345, -0.0062],
          [ 0.0074,  0.0160, -0.0298,  0.0135,  0.0214, -0.0096]]]])
tensor([[[[0.3360, 0.3232, 0.3438, 0.3439, 0.3299, 0.3455]]]],
       grad_fn=<SigmoidBackward0>)


<ipython-input-9-9a17e629dd26>:12: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  torch.nn.init.xavier_uniform(conv1.weight)


In [35]:
xs_head.view(3, -1)

tensor([[0.8868, 1.2021, 0.0000, 0.1207, 0.9510, 1.5009, 0.3355, 0.6886],
        [1.5549, 1.9498, 0.5409, 1.4537, 2.0696, 1.8772, 1.0826, 1.5081],
        [2.2604, 2.6974, 1.3812, 2.7866, 3.2069, 2.2535, 1.8707, 2.3276]],
       grad_fn=<ViewBackward0>)

In [15]:
x = torch.tensor([[1,2,3],[4,5,6]])
x[:, 0].tolist() + x[:, 2].tolist()

[1, 4, 3, 6]

In [12]:
import torch
from numpy.random import choice
import numpy as np

ids = np.array([1,2,3])
torch.from_numpy(choice(a=ids, size=10))

tensor([1, 2, 3, 2, 3, 3, 2, 1, 1, 3])

In [14]:
torch.unique(torch.tensor([1,2,3,4])).numpy()

array([1, 2, 3, 4])

In [17]:
from torch_geometric.utils import subgraph

edge_index = torch.tensor([[0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6], [1, 0, 2, 1, 3, 2, 4, 3, 5, 4, 6, 5]])
edge_attr = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
subset = torch.tensor([3, 4, 5])
x, y = subgraph(subset, edge_index, edge_attr)

In [18]:
z = torch.tensor([[1,2,3], [4,5,6]])


In [20]:
torch.cat((x,z), dim=1)

tensor([[3, 4, 4, 5, 1, 2, 3],
        [4, 3, 5, 4, 4, 5, 6]])