In [1]:
from torch_geometric.loader import NeighborLoader, NeighborSampler

/homes/mblum/miniconda3/envs/lp/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
import torch
from torch_geometric.data import Data

edge_index = torch.tensor([[0, 1, 1, 2, 0],
                           [1, 0, 2, 1, 3]], dtype=torch.long)
x = torch.tensor([[-1], [0], [1]], dtype=torch.float)

data = Data(x=x, edge_index=edge_index)

In [3]:
data.edge_index[0]==1


tensor([False,  True,  True, False, False])

In [4]:
graphs = [
    Data(edge_index=torch.tensor([[1,2,3],[4,5,6]])),
    Data(edge_index=torch.tensor([[4,2,5],[9,5,8]]))
]

g = [graphs[i].edge_index for i in torch.tensor([0,1])]

edge_index = torch.cat(g, dim=1)


In [5]:
edge_index

tensor([[1, 2, 3, 4, 2, 5],
        [4, 5, 6, 9, 5, 8]])

In [6]:
torch.save(
           graphs, 'tensor.pt')

In [9]:
import numpy as np

l = np.array([[0, 1], [1, 4], [1, 5], [1, 6], [0, 2], [2, 7], [0, 3], [3, 8], [3, 9], [3, 10], [3, 11]]).transpose()
r = np.array([l[1, :], l[0, :]])
edge_index = torch.from_numpy(r)

train_loader = NeighborSampler(edge_index,
                               sizes=[2, 2], batch_size=1)

for batch_size, n_id, adjs in train_loader:
    print("###")
    print(n_id)
    for edge_ind, e_id, size in adjs:
        print(e_id)
        print(edge_ind)

###
tensor([0, 2, 1, 3, 7, 5, 4])
tensor([0, 6, 5, 2, 1])
tensor([[2, 3, 4, 5, 6],
        [0, 0, 1, 2, 2]])
tensor([4, 0])
tensor([[1, 2],
        [0, 0]])
###
tensor([1, 6, 4, 5])
tensor([1, 2])
tensor([[2, 3],
        [0, 0]])
tensor([3, 1])
tensor([[1, 2],
        [0, 0]])
###
tensor([2, 7])
tensor([5])
tensor([[1],
        [0]])
tensor([5])
tensor([[1],
        [0]])
###
tensor([ 3,  9,  8, 11])
tensor([ 8, 10])
tensor([[1, 3],
        [0, 0]])
tensor([8, 7])
tensor([[1, 2],
        [0, 0]])
###
tensor([4])
tensor([], dtype=torch.int64)
tensor([], size=(2, 0), dtype=torch.int64)
tensor([], dtype=torch.int64)
tensor([], size=(2, 0), dtype=torch.int64)
###
tensor([5])
tensor([], dtype=torch.int64)
tensor([], size=(2, 0), dtype=torch.int64)
tensor([], dtype=torch.int64)
tensor([], size=(2, 0), dtype=torch.int64)
###
tensor([6])
tensor([], dtype=torch.int64)
tensor([], size=(2, 0), dtype=torch.int64)
tensor([], dtype=torch.int64)
tensor([], size=(2, 0), dtype=torch.int64)
###
tensor([

In [18]:
edge_index = torch.tensor([[0, 1, 2, 3, 4, 5], [2, 2, 4, 4, 6, 6]])
print(edge_index.T)
x = torch.zeros((7, 200))

tensor([[0, 2],
        [1, 2],
        [2, 4],
        [3, 4],
        [4, 6],
        [5, 6]])


In [21]:
from torch_geometric.utils import k_hop_subgraph
# Center node 6, 2-hops
subset, edge_index, mapping, edge_mask = k_hop_subgraph([5,6], 1, edge_index, relabel_nodes=True, directed=False)


In [22]:
subset

tensor([4, 5, 6])

In [23]:
edge_index

tensor([[0, 1],
        [2, 2]])

In [19]:
x[subset]

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 

In [20]:
edge_type[edge_mask]


tensor([False, False, False, False,  True,  True])

In [28]:
mapping = torch.tensor([1,2,3,4])

In [35]:
mapping.size(0)/2

2.0

In [36]:
mapping[:int(mapping.size(0)/2)], mapping[int(mapping.size(0)/2):]

(tensor([1, 2]), tensor([3, 4]))

In [2]:
import torch

In [3]:
page_links = torch.load('../data/wikidata5m_inductive/page_links.pt')

In [4]:
from torch_geometric.utils import k_hop_subgraph

/homes/mblum/miniconda3/envs/lp/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [6]:
page_links.T.size()

torch.Size([2, 100109235])

In [14]:
subset, edge_index, mapping, edge_mask = k_hop_subgraph(torch.tensor([1]), 1, page_links.T, relabel_nodes=True, directed=False)

In [15]:
subset

tensor([      1,   54519, 2260712])

In [12]:
mapping

tensor([0, 1, 2, 3])

In [16]:
import torch
hops = torch.load(f'../data/wikidata5m_inductive/hops.pt')

In [ ]:
hops.edge_index