In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer
from tqdm import tqdm
from sklearn.metrics.pairwise import cosine_similarity
import json
import torch
import json

In [17]:
corpus_inductive = []
corpus_all = []

with open('../data/wikidata5m_inductive/uri_to_id.json') as i:
    uri_to_id = json.load(i)

data_val = torch.load(f'../data/wikidata5m_inductive/val.pt')
data_test = torch.load(f'../data/wikidata5m_inductive/test.pt')

inductive_entities = torch.unique(torch.cat((data_val.edge_index[0],
                                                     data_val.edge_index[1],
                                                     data_test.edge_index[0],
                                                     data_test.edge_index[1]))).tolist()



In [19]:
with open('../data/wikidata5m_inductive/wikidata5m_text.txt') as descriptions_in:
    for line in tqdm(descriptions_in, total=5000000):
        splitted = line.split('\t')
        uri, description = splitted[0], splitted[1]
        if uri_to_id[uri] not in inductive_entities:
            corpus_inductive.append(description)
        corpus_all.append(description)

 96%|█████████▋| 4815483/5000000 [05:54<00:13, 13579.50it/s]


In [20]:
vectorizer = TfidfVectorizer(stop_words='english')
vectorizer.fit(corpus_inductive)

TfidfVectorizer(stop_words='english')

In [21]:
x = vectorizer.transform(corpus_all)

In [13]:
print(x[0])

  (0, 2811113)	0.07727453986632345
  (0, 591485)	0.03822560152626008
  (0, 3188771)	0.05791699696250275
  (0, 278475)	0.06548163128792112
  (0, 1752684)	0.02875625634386119
  (0, 178357)	0.07057612122963013
  (0, 1003523)	0.05353696127383455
  (0, 462799)	0.06212207198635179
  (0, 1457672)	0.06626762035789545
  (0, 3334620)	0.07117357227136162
  (0, 1089212)	0.05709775258951615
  (0, 1996394)	0.05306103452079006
  (0, 1457626)	0.04814321408325634
  (0, 1115520)	0.08084428555087406
  (0, 168093)	0.04110769635306805
  (0, 1224498)	0.0388947556378214
  (0, 3306088)	0.03701311608628776
  (0, 1463480)	0.07080534382978969
  (0, 2876665)	0.1608599386398331
  (0, 1446713)	0.08560222366113351
  (0, 1368377)	0.04810711665636337
  (0, 3277599)	0.0514313251459881
  (0, 3338897)	0.039357291731695734
  (0, 986970)	0.1319554820034015
  (0, 1742037)	0.03778465593108841
  :	:
  (0, 2568186)	0.11201105768633043
  (0, 545450)	0.035673874159226536
  (0, 1801977)	0.035715071216500485
  (0, 1240674)	0.04483

  (0, 3029257)	1.0


In [25]:
cosine_sim = cosine_similarity(x[0], x[14])
print(cosine_sim)

[[0.00537631]]


In [10]:
from scipy import sparse
# faster to use the npz numpy file!
s#parse.save_npz('../data/wikidata5m_inductive/tfidf_features_ind.npz', x)
# how to load:
# x = sparse.load_npz('../data/wikidata5m_inductive/tfidf_features.npz')


In [26]:
torch.save(x, '../data/wikidata5m_inductive/tfidf_features_inductive.pt')

In [27]:
k = torch.load('../data/wikidata5m_inductive/tfidf_features_inductive.pt')

In [17]:
from sklearn.metrics.pairwise import cosine_similarity
cosine_sim = cosine_similarity([x[0], x[9]])
cosine_sim

ValueError: setting an array element with a sequence.

In [14]:
print(k[0])

  (0, 2817021)	0.07724725017925207
  (0, 592870)	0.0382208101146961
  (0, 3195352)	0.05791789509341351
  (0, 279219)	0.06545553243216483
  (0, 1756329)	0.02875493227499248
  (0, 178890)	0.07054007598430072
  (0, 1005792)	0.05353974903320097
  (0, 463922)	0.06212201277448217
  (0, 1460817)	0.06626717652563598
  (0, 3341485)	0.07116313471221578
  (0, 1091641)	0.057094933200909866
  (0, 2000612)	0.0530432417939497
  (0, 1460771)	0.04814323990994024
  (0, 1118018)	0.08082544518017783
  (0, 168601)	0.04111218264451025
  (0, 1227207)	0.038892766379683974
  (0, 3312906)	0.037014275875305445
  (0, 1466645)	0.07080609961855235
  (0, 2882720)	0.1608265687356716
  (0, 1449838)	0.08562189001191592
  (0, 1371344)	0.048101335812803514
  (0, 3284382)	0.05142599051816527
  (0, 3345786)	0.03935490208176332
  (0, 989203)	0.13196618165492383
  (0, 1745659)	0.03778659334471948
  :	:
  (0, 2573615)	0.11202458842223612
  (0, 546757)	0.03568096464064023
  (0, 1805767)	0.035725446405517225
  (0, 1243412)	0.04

In [69]:
x = torch.load('../data/wikidata5m_inductive/entity_description_first_sentence_embedding.pt')

In [32]:
x

tensor([[ 0.0849,  0.0310, -0.0396,  ...,  0.0351,  0.0726,  0.0102],
        [-0.0232,  0.0864, -0.0948,  ...,  0.0643,  0.0029, -0.0484],
        [ 0.0534, -0.0389,  0.0421,  ..., -0.0390,  0.0267,  0.0127],
        ...,
        [-0.0757,  0.0246, -0.0476,  ..., -0.0566,  0.0126, -0.0067],
        [-0.0425,  0.0208, -0.0873,  ..., -0.0584, -0.0151,  0.0814],
        [-0.0249,  0.0120, -0.0359,  ..., -0.0055,  0.0415,  0.0298]])

In [70]:
cos = torch.nn.CosineSimilarity(dim=1)
neighbors = x[[1,21, 31, 4,5, 0]]
head = x[0]
head_stacked = head.repeat((neighbors.size(0),1))
print(head_stacked.size())
cos(head_stacked, neighbors)


torch.Size([6, 384])


tensor([ 0.1458, -0.0589, -0.0683,  0.0238, -0.0313,  1.0000])

tensor(-0.0948)

In [53]:
from collections import Counter

Counter([5,3,5,7,3])

Counter({5: 2, 3: 2, 7: 1})

In [66]:
from torch_geometric.data import Data
from torch_geometric.transforms import RemoveDuplicatedEdges

transform = RemoveDuplicatedEdges()
out = transform(Data(x=torch.tensor([]), edge_index=torch.tensor( [[1,2,1],[1,2,1]]))).edge_index

In [67]:
out

tensor([[1, 2],
        [1, 2]])

In [3]:
tfidf_feature_vectors = torch.load('../data/wikidata5m_inductive/tfidf_features.pt')

In [13]:
torch.from_numpy(tfidf_feature_vectors[[1,2]].todense())

tensor([[0., 0., 0.,  ..., 0., 0., 0.],
        [0., 0., 0.,  ..., 0., 0., 0.]], dtype=torch.float64)

In [4]:
head_features_stacked = tfidf_feature_vectors[5].repeat((5, 1))

AttributeError: repeat not found

In [8]:
cos = torch.nn.CosineSimilarity(dim=1)

head = torch.from_numpy(tfidf_feature_vectors[[1,2]].todense())

cos(tfidf_feature_vectors[5].to_dense(), tfidf_feature_vectors[5].to_dense())

AttributeError: to_dense not found

In [10]:
from sklearn.metrics.pairwise import cosine_similarity
import torch
from scipy import sparse

cosine_sim = cosine_similarity(tfidf_feature_vectors[[0,1,1,2,3,4,5,6,7]])[0]
cosine_sim

array([1.        , 0.0181096 , 0.0181096 , 0.02673764, 0.        ,
       0.        , 0.00157571, 0.03113341, 0.        ])