In [2]:
from pykeen.triples import TriplesFactory
from pykeen.pipeline import pipeline
from tqdm import tqdm 

/homes/mblum/miniconda3/envs/lp/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [7]:
result = pipeline(
    training='../data/corpus_graphs/trex_triples_filtered_100_hop_1_sim_0.2845.txt',
    testing='../data/corpus_graphs/inference_test_filtered_ilpc.txt',
    model='DistMult',
    #stopper='early',  # todo causes an issue for some reason when the evaluation starts, therefore, check entitiy and relation overlap between train and test!
    epochs=50,
    device='gpu',
    model_kwargs=dict(embedding_dim=200),
)

INFO:pykeen.pipeline.api:Using device: gpu
Training batches on cuda:0:  65%|██████▌   | 523/801 [00:02<00:01, 203.42batch/s]


Training batches on cuda:0:  44%|████▍     | 354/801 [00:01<00:02, 200.58batch/s]


Training batches on cuda:0:  20%|██        | 163/801 [00:00<00:03, 197.41batch/s]


Training batches on cuda:0:  87%|████████▋ | 700/801 [00:03<00:00, 198.71batch/s]


Training batches on cuda:0:  63%|██████▎   | 504/801 [00:02<00:01, 194.94batch/s]


Training batches on cuda:0:  49%|████▊     | 389/801 [00:03<00:02, 200.24batch/s]


Training batches on cuda:0:  10%|█         | 81/801 [00:00<00:03, 198.24batch/s]


Training batches on cuda:0:  62%|██████▏   | 499/801 [00:02<00:01, 199.75batch/s]


Training batches on cuda:0:  36%|███▋      | 292/801 [00:01<00:02, 203.45batch/s]


Training batches on cuda:0:  15%|█▌        | 123/801 [00:00<00:03, 201.74batch/s]


Training epochs on cuda:0: 100%|██████████| 50/50 [03:37<00:00,  4.34s/epoch, loss=0.33, prev_loss=0.331] 
INFO:pykeen.evaluation.evaluator:Starting batch_size search for evaluation now...
INFO:pykeen.evaluation.evaluator:Concluded batch_size search with batch_size=512.
Evaluating on cuda:0: 100%|██████████| 2.20k/2.20k [00:01<00:00, 1.86ktriple/s]
INFO:pykeen.evaluation.evaluator:Evaluation took 1.91s seconds


In [8]:
result.get_metric('mrr')

0.0888766422867775

In [ ]:
result.pipeline

In [ ]:
result.metric_results

In [3]:
result = pipeline(
    dataset="Wikidata5M",
    model='DistMult',
    stopper='early',
    epochs=100,
    device='cpu',
    model_kwargs=dict(embedding_dim=512),
)

No random seed is specified. Setting to 3672080562.
Training epochs on cpu:   0%|          | 0/100 [02:59<?, ?epoch/s]                


KeyboardInterrupt: 

In [4]:
from torch_geometric.utils import degree

edge_index = [[1,1,1], [2,2,2]]
deg = degree(edge_index[0], 3)

AttributeError: 'list' object has no attribute 'device'

In [12]:
embeddings_dict = {}
with open('../data/corpus_graphs/trex_triples_filtered_100_hop_1_ilpc_train_embeddings.txt', 'r') as embeddings_in:
    for line in tqdm(embeddings_in, total=3708248):
        line = line[:-1]
        entitiy = line.split(' ')[0]
        embedding = line.split(' ')[1:]
        embeddings_dict[entitiy] = embedding
        

  2%|▏         | 69141/3708248 [00:04<03:31, 17246.24it/s]


In [ ]:
from pykeen.triples import TriplesFactory
from pykeen.pipeline import pipeline
from pykeen.datasets.nations import NATIONS_TRAIN_PATH, NATIONS_TEST_PATH
training = TriplesFactory.from_path(
    '../data/corpus_graphs/trex_triples_filtered_100_hop_1_ilpc_train.txt',
    create_inverse_triples=True)

testing = TriplesFactory.from_path(
    '../data/corpus_graphs/inference_test_filtered_ilpc.txt',
    entity_to_id=training.entity_to_id,
    relation_to_id=training.relation_to_id,
    create_inverse_triples=True,
)

result = pipeline(
    training=training,
    testing=testing,
    model='TransE',
    epochs=5,  # short epochs for testing - you should go higher
)

In [3]:
import torch
from pykeen.pipeline import pipeline


#num_entities = 14
#pretrained_embedding_tensor = torch.rand(num_entities, 128)


#def initialize_from_pretrained(x: torch.FloatTensor) -> torch.FloatTensor:
#    print(x)
#    return pretrained_embedding_tensor


result = pipeline(
    dataset="wikidata5m",
    model="DistMult",
)

No random seed is specified. Setting to 4167099614.
Training epochs on cuda:0:   0%|          | 0/5 [00:14<?, ?epoch/s]                 

KeyboardInterrupt



In [6]:
import torch

In [7]:
head = torch.tensor([1,2,3,4,5,6,7,8])

In [11]:
torch.split(head, 5)

(tensor([1, 2, 3, 4, 5]), tensor([6, 7, 8]))

In [13]:
out = [torch.tensor([1,2,3]), torch.tensor([1,2])]

In [14]:
torch.cat(out)

tensor([1, 2, 3, 1, 2])

In [21]:
a = torch.tensor([[1,2,3],[4,5,6]])
b = torch.tensor([[1,2,3],[4,5,6]])
torch.cat((a,b), dim=1)

tensor([[1, 2, 3, 1, 2, 3],
        [4, 5, 6, 4, 5, 6]])

In [27]:
from easydict import EasyDict

ModuleNotFoundError: No module named 'easydict'

In [1]:
import pickle

with open("../data/wikidata5m_inductive/distmult_wikidata5m.pkl", "rb") as fin:
    model = pickle.load(fin)
entity2id = model.graph.entity2id
relation2id = model.graph.relation2id
entity_embeddings = model.solver.entity_embeddings
relation_embeddings = model.solver.relation_embeddings

In [2]:
entity2id

{'Q29387131': 0,
 'Q5': 1,
 'Q326660': 2,
 'Q652': 3,
 'Q7339549': 4,
 'Q1365729': 5,
 'Q554335': 6,
 'Q29999': 7,
 'Q20641639': 8,
 'Q80955': 9,
 'Q14946683': 10,
 'Q4221140': 11,
 'Q399': 12,
 'Q6925786': 13,
 'Q488653': 14,
 'Q4890993': 15,
 'Q931116': 16,
 'Q3198638': 17,
 'Q2859200': 18,
 'Q24905727': 19,
 'Q88139': 20,
 'Q710987': 21,
 'Q674095': 22,
 'Q7173419': 23,
 'Q1434796': 24,
 'Q465806': 25,
 'Q3391415': 26,
 'Q11469296': 27,
 'Q26600': 28,
 'Q14573913': 29,
 'Q189290': 30,
 'Q28051650': 31,
 'Q1778168': 32,
 'Q3302612': 33,
 'Q1069071': 34,
 'Q7827136': 35,
 'Q36074': 36,
 'Q16030681': 37,
 'Q4117588': 38,
 'Q6076643': 39,
 'Q876191': 40,
 'Q4935581': 41,
 'Q6608367': 42,
 'Q1046542': 43,
 'Q34740': 44,
 'Q17015941': 45,
 'Q1190554': 46,
 'Q5915589': 47,
 'Q739': 48,
 'Q4102888': 49,
 'Q2631868': 50,
 'Q3445500': 51,
 'Q4430810': 52,
 'Q16766': 53,
 'Q3946132': 54,
 'Q19490': 55,
 'Q7523417': 56,
 'Q5375': 57,
 'Q4380937': 58,
 'Q571': 59,
 'Q7361422': 60,
 'Q532': 61,
 

In [8]:
len(entity_embeddings[0])

512

In [6]:
import json
ENTITY_2_ID_FILE = '../data/wikidata5m_inductive/uri_to_id.json'
with open(ENTITY_2_ID_FILE) as uri_to_id_in:
    uri_to_id = json.load(uri_to_id_in)


In [17]:
import torch
x = torch.zeros((len(uri_to_id.keys()), 512))
our_entities = set(uri_to_id.keys())
for e in entity2id.keys():
    if e in our_entities:
        x[uri_to_id[e]] = torch.tensor(entity_embeddings[entity2id[e]])
    

In [19]:
torch.save(x, f'../data/wikidata5m_inductive/distmult_pretrained.pt')